version: "3.8"

services:
  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput && gunicorn property.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=glassbricks
      - POSTGRES_USER=glassbrix
      - POSTGRES_PASSWORD=glassbrix
      - POSTGRES_HOST=193.22.147.76
      - POSTGRES_PORT=5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
