version: "3.8"

services:
  web:
    build: .
    command: gunicorn property.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=glassbricks
      - POSTGRES_USER=glassbrix
      - POSTGRES_PASSWORD=glassbrix
      - POSTGRES_HOST=193.22.147.76   # Directly using the IP address
      - POSTGRES_PORT=5432  # Default PostgreSQL port
    networks:
      - backend

networks:
  backend:
    driver: bridge
