# Generated by Django 4.2.10 on 2024-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0004_rename_propertyform_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='apartment_no',
            new_name='appartment',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='posted_by',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='property_type1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='specific_type',
            new_name='specific_type1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='availability_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='property',
            name='specific_type2',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
