# Generated by Django 4.2.10 on 2024-08-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0005_rename_apartment_no_property_appartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='poster',
            new_name='posted_by',
        ),
    ]
