# Generated by Django 4.2.10 on 2024-09-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0007_remove_property_video_propertyvideo_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
