# Generated by Django 4.2.10 on 2024-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0008_property_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvideo',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='videos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='PropertyVideo',
        ),
    ]
