# Generated by Django 4.2.10 on 2024-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0016_alter_property_floor_plan_alter_property_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='videos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
