# Generated by Django 4.2.10 on 2024-09-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0018_remove_property_floor_plan_remove_property_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfloorplan',
            name='floor_plan',
            field=models.ImageField(upload_to='property_floor_plan/'),
        ),
    ]
