# Generated by Django 4.2.10 on 2024-09-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0020_alter_propertyfloorplan_floor_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='specific_type2',
        ),
    ]
