# Generated by Django 4.2.10 on 2024-08-27 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=10)),
                ('property_type', models.CharField(max_length=15)),
                ('specific_type', models.CharField(max_length=20)),
                ('maharera_number', models.CharField(blank=True, max_length=50, null=True)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('balconies', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ownership', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('apartment_no', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='glassbricks.propertyform')),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
