# Generated by Django 4.2.10 on 2024-09-20 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0012_alter_property_city_alter_property_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='appartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_floor_plan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='property',
            name='videos',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='property_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
    ]
