# Generated by Django 4.2.10 on 2024-09-21 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0013_alter_property_address_alter_property_appartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, max_length=3000, null=True, upload_to='property_floor_plan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, max_length=3000, null=True, upload_to='property_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='property',
            name='videos',
            field=models.FileField(blank=True, max_length=3000, null=True, upload_to='property_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
    ]
