# Generated by Django 4.2.10 on 2024-09-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glassbricks', '0017_alter_property_floor_plan_alter_property_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.RemoveField(
            model_name='property',
            name='videos',
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='property_videos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='glassbricks.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='glassbricks.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_plan', models.ImageField(upload_to='property_floor_plans/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='glassbricks.property')),
            ],
        ),
    ]
