name: Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (or your preferred branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass (for SSH password authentication)
      run: sudo apt-get install -y sshpass

    - name: Deploy to VPS using SSH Password
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_SSH_PASSWORD: ${{ secrets.VPS_SSH_PASSWORD }}
      run: |
        # Using sshpass with SSH password to connect to VPS
        echo "Starting deployment process on VPS..."

        # Connect via SSH, pull latest code, and collect static files
        sshpass -p $VPS_SSH_PASSWORD ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP <<EOF
          echo "Changing directory to /root/glass-main..."
          cd /root/glass-main

          echo "Pulling latest changes from the main branch..."
          git pull origin main

          # Run collectstatic before restarting containers
          echo "Running collectstatic..."
          python manage.py collectstatic --noinput

          echo "Stopping and removing existing containers..."
          docker-compose down

          echo "Building and restarting containers..."
          docker-compose up -d --build

          echo "Deployment completed!"
        EOF
